/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lyricgen.UI_Elements;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lyricgen.mysqlStorage;

/**
 *
 * @author noah
 */
public class Community extends javax.swing.JPanel {

    /**
     * Creates new form Community
     */
    public Community() {
        initComponents();
        
        //set the model to a new blank model
        //then add more columns
        jTable1.setModel(new DefaultTableModel(){
            //This makes it so that you CANNOT edit any of the cells, which we don't want
            @Override
            public boolean isCellEditable(int row, int column){  
                return false;  
            }
        });
        DefaultTableModel jTableModel = (DefaultTableModel) jTable1.getModel();
        //add each column
        jTableModel.addColumn("id");
        jTableModel.addColumn("lyrics");
        jTableModel.addColumn("Title");
        jTableModel.addColumn("Artist");
        jTableModel.addColumn("Release Date");
        
        //Remove the column from the jTable but not from the Table Model
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0)); //id
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0)); //lyrics index - 1
        
        try {
            //get all things from songs
            ResultSet rsSongs = mysqlStorage.sqlHandler.executeQuery("SELECT * FROM user_songs ORDER BY submit_date DESC;");
            while( rsSongs.next() ) {
                //Long string[], basically puts all of the rsSongs properties into the table in the right slots
                String usernameFromId = mysqlStorage.sqlHandler.getUserFromId(rsSongs.getInt("user_id")).get("username").toString();
                jTableModel.addRow(new String[]{String.format("%s",rsSongs.getInt("id")), rsSongs.getString("lyrics"), rsSongs.getString("title"), usernameFromId, rsSongs.getString("submit_date")});
            }
        } catch(SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(185, 207, 212));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Recently Published");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.rowAtPoint(evt.getPoint());
        //Get the model of the table
        TableModel jTableModel = jTable1.getModel();
        // gather info
        String lyrics = (String) jTableModel.getValueAt(row, 1);
        String title = (String) jTableModel.getValueAt(row, 2);
        String artist = (String) jTableModel.getValueAt(row, 3);
        // show the song
        viewSong newViewSong = new viewSong(lyrics, title, artist);
        newViewSong.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
